apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: daocloud.io/daocloud/nfs-client-provisioner
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 192.168.176.90
            - name: NFS_PATH
              value: /var/lib/docker/nfs1
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.176.90
            path: /var/lib/docker/nfs1
